// src/components/CountryList.js

const CountryList = () => {
  return [
    { value: 'AFG', label: 'Afghanistan', countryCode: '+93' },
    { value: 'ALB', label: 'Albania', countryCode: '+355' },
    { value: 'DZA', label: 'Algeria', countryCode: '+213' },
    { value: 'AND', label: 'Andorra', countryCode: '+376' },
    { value: 'AGO', label: 'Angola', countryCode: '+244' },
    { value: 'ATG', label: 'Antigua and Barbuda', countryCode: '+1-268' },
    { value: 'ARG', label: 'Argentina', countryCode: '+54' },
    { value: 'ARM', label: 'Armenia', countryCode: '+374' },
    { value: 'AUS', label: 'Australia', countryCode: '+61' },
    { value: 'AUT', label: 'Austria', countryCode: '+43' },
    { value: 'AZE', label: 'Azerbaijan', countryCode: '+994' },
    { value: 'BHS', label: 'Bahamas', countryCode: '+1-242' },
    { value: 'BHR', label: 'Bahrain', countryCode: '+973' },
    { value: 'BGD', label: 'Bangladesh', countryCode: '+880' },
    { value: 'BRB', label: 'Barbados', countryCode: '+1-246' },
    { value: 'BLR', label: 'Belarus', countryCode: '+375' },
    { value: 'BEL', label: 'Belgium', countryCode: '+32' },
    { value: 'BLZ', label: 'Belize', countryCode: '+501' },
    { value: 'BEN', label: 'Benin', countryCode: '+229' },
    { value: 'BTN', label: 'Bhutan', countryCode: '+975' },
    { value: 'BOL', label: 'Bolivia', countryCode: '+591' },
    { value: 'BES', label: 'Bonaire, Sint Eustatius and Saba', countryCode: '+599' },
    { value: 'BIH', label: 'Bosnia and Herzegovina', countryCode: '+387' },
    { value: 'BWA', label: 'Botswana', countryCode: '+267' },
    { value: 'BVT', label: 'Bouvet Island', countryCode: '+47' },
    { value: 'BRA', label: 'Brazil', countryCode: '+55' },
    { value: 'VGB', label: 'British Virgin Islands', countryCode: '+1-284' },
    { value: 'BRN', label: 'Brunei Darussalam', countryCode: '+673' },
    { value: 'BGR', label: 'Bulgaria', countryCode: '+359' },
    { value: 'BFA', label: 'Burkina Faso', countryCode: '+226' },
    { value: 'BDI', label: 'Burundi', countryCode: '+257' },
    { value: 'CPV', label: 'Cabo Verde', countryCode: '+238' },
    { value: 'KHM', label: 'Cambodia', countryCode: '+855' },
    { value: 'CMR', label: 'Cameroon', countryCode: '+237' },
    { value: 'CAN', label: 'Canada', countryCode: '+1' },
    { value: 'CYM', label: 'Cayman Islands', countryCode: '+1-345' },
    { value: 'CAF', label: 'Central African Republic', countryCode: '+236' },
    { value: 'TCD', label: 'Chad', countryCode: '+235' },
    { value: 'CHL', label: 'Chile', countryCode: '+56' },
    { value: 'CHN', label: 'China', countryCode: '+86' },
    { value: 'CXR', label: 'Christmas Island', countryCode: '+61' },
    { value: 'CCK', label: 'Cocos (Keeling) Islands', countryCode: '+61' },
    { value: 'COL', label: 'Colombia', countryCode: '+ 57' },
    { value: 'COM', label: 'Comoros', countryCode: '+269' },
    { value: 'COG', label: 'Congo', countryCode: '+242' },
    { value: 'COK', label: 'Cook Islands', countryCode: '+682' },
    { value: 'CRI', label: 'Costa Rica', countryCode: '+506' },
    { value: 'CIV', label: "Côte d'Ivoire", countryCode: '+225' },
    { value: 'HRV', label: 'Croatia', countryCode: '+385' },
    { value: 'CUB', label: 'Cuba', countryCode: '+53' },
    { value: 'CUW', label: 'Curaçao', countryCode: '+599' },
    { value: 'CYP', label: 'Cyprus', countryCode: '+357' },
    { value: 'CZE', label: 'Czech Republic', countryCode: '+420' },
    { value: 'DNK', label: 'Denmark', countryCode: '+45' },
    { value: 'DJI', label: 'Djibouti', countryCode: '+253' },
    { value: 'DMA', label: 'Dominica', countryCode: '+1-767' },
    { value: 'DOM', label: 'Dominican Republic', countryCode: '+1-809' },
    { value: 'ECU', label: 'Ecuador', countryCode: '+593' },
    { value: 'EGY', label: 'Egypt', countryCode: '+20' },
    { value: 'SLV', label: 'El Salvador', countryCode: '+503' },
    { value: 'GNQ', label: 'Equatorial Guinea', countryCode: '+240' },
    { value: 'ERI', label: 'Eritrea', countryCode: '+291' },
    { value: 'EST', label: 'Estonia', countryCode: '+372' },
    { value: 'SWZ', label: 'Eswatini', countryCode: '+268' },
    { value: 'ETH', label: 'Ethiopia', countryCode: '+251' },
    { value: 'FLK', label: 'Falkland Islands (Malvinas)', countryCode: '+500' },
    { value: 'FRO', label: 'Faroe Islands', countryCode: '+298' },
    { value: 'FJI', label: 'Fiji', countryCode: '+679' },
    { value: 'FIN', label: 'Finland', countryCode: '+358' },
    { value: 'FRA', label: 'France', countryCode: '+33' },
    { value: 'GUF', label: 'French Guiana', countryCode: '+594' },
    { value: 'PYF', label: 'French Polynesia', countryCode: '+689' },
    { value: 'ATF', label: 'French Southern Territories', countryCode: '+262' },
    { value: 'GAB', label: 'Gabon', countryCode: '+241' },
    { value: 'GMB', label: 'Gambia', countryCode: '+220' },
    { value: 'GEO', label: 'Georgia', countryCode: '+995' },
    { value: 'DEU', label: 'Germany', countryCode: '+49' },
    { value: 'GHA', label: 'Ghana', countryCode: '+233' },
    { value: 'GIB', label: 'Gibraltar', countryCode: '+350' },
    { value: 'GRC', label: 'Greece', countryCode: '+30' },
    { value: 'GRL', label: 'Greenland', countryCode: '+299' },
    { value: 'GRD', label: 'Grenada', countryCode: '+1-473' },
    { value: 'GLP', label: 'Guadeloupe', countryCode: '+590' },
    { value: 'GUM', label: 'Guam', countryCode: '+1-671' },
    { value: 'GUA', label: 'Guatemala', countryCode: '+502' },
    { value: 'GGY', label: 'Guernsey', countryCode: '+44-1481' },
    { value: 'GIN', label: 'Guinea', countryCode: '+224' },
    { value: 'GNB', label: 'Guinea-Bissau', countryCode: '+245' },
    { value: 'GUY', label: 'Guyana', countryCode: '+592' },
    { value: 'HTI ', label: 'Haiti', countryCode: '+509' },
    { value: 'HMD', label: 'Heard Island and McDonald Islands', countryCode: '+61' },
    { value: 'HND', label: 'Honduras', countryCode: '+504' },
    { value: 'HKG', label: 'Hong Kong', countryCode: '+852' },
    { value: 'HUN', label: 'Hungary', countryCode: '+36' },
    { value: 'ISL', label: 'Iceland', countryCode: '+354' },
    { value: 'IND', label: 'India', countryCode: '+91' },
    { value: 'IDN', label: 'Indonesia', countryCode: '+62' },
    { value: 'IRN', label: 'Iran', countryCode: '+98' },
    { value: 'IRQ', label: 'Iraq', countryCode: '+964' },
    { value: 'IRL', label: 'Ireland', countryCode: '+353' },
    { value: 'IMN', label: 'Isle of Man', countryCode: '+44-1624' },
    { value: 'ISR', label: 'Israel', countryCode: '+972' },
    { value: 'ITA', label: 'Italy', countryCode: '+39' },
    { value: 'JAM', label: 'Jamaica', countryCode: '+1-876' },
    { value: 'JPN', label: 'Japan', countryCode: '+81' },
    { value: 'JEY', label: 'Jersey', countryCode: '+44-1534' },
    { value: 'JOR', label: 'Jordan', countryCode: '+962' },
    { value: 'KAZ', label: 'Kazakhstan', countryCode: '+7' },
    { value: 'KEN', label: 'Kenya', countryCode: '+254' },
    { value: 'KIR', label: 'Kiribati', countryCode: '+686' },
    { value: 'KOR', label: 'Korea', countryCode: '+82' },
    { value: 'KWT', label: 'Kuwait', countryCode: '+965' },
    { value: 'KGZ', label: 'Kyrgyzstan', countryCode: '+996' },
    { value: 'LAO', label: "Lao People's Democratic Republic", countryCode: '+856' },
    { value: 'LVA', label: 'Latvia', countryCode: '+371' },
    { value: 'LBN', label: 'Lebanon', countryCode: '+961' },
    { value: 'LSO', label: 'Lesotho', countryCode: '+266' },
    { value: 'LBR', label: 'Liberia', countryCode: '+231' },
    { value: 'LBY', label: 'Libya', countryCode: '+218' },
    { value: 'LIE', label: 'Liechtenstein', countryCode: '+423' },
    { value: 'LTU', label: 'Lithuania', countryCode: '+370' },
    { value: 'LUX', label: 'Luxembourg', countryCode: '+352' },
    { value: 'MAC', label: 'Macao', countryCode: '+853' },
    { value: 'MDG', label: 'Madagascar', countryCode: '+261' },
    { value: 'MWI', label: 'Malawi', countryCode: '+265' },
    { value: 'MYS', label: 'Malaysia', countryCode: '+60' },
    { value: 'MDV', label: 'Maldives', countryCode: '+960' },
    { value: 'MLI', label: 'Mali', countryCode: '+223' },
    { value: 'MLT', label: 'Malta', countryCode: '+356' },
    { value: 'MHL', label: 'Marshall Islands', countryCode: '+692' },
    { value: 'MTQ', label: 'Martinique', countryCode: '+596' },
    { value: 'MRT', label: 'Mauritania', countryCode: '+222' },
    { value: 'MUS', label: 'Mauritius', countryCode: '+230' },
    { value: 'MYT', label: 'Mayotte', countryCode: '+262' },
    { value: 'MEX', label: 'Mexico', countryCode: '+52' },
    { value: 'FSM', label: 'Micronesia', countryCode: '+691' },
    { value: 'MDA', label: 'Moldova', countryCode: '+373' },
    { value: 'MCO', label: 'Monaco', countryCode: '+377' },
    { value: 'MNG', label: 'Montenegro', countryCode: '+382' },
    { value: 'MSR', label: 'Montserrat', countryCode: '+1-664' },
    { value: 'MAR', label: 'Morocco', countryCode: '+212' },
    { value: 'MOZ', label: 'Mozambique', countryCode: '+258' },
    { value: 'MMR', label: 'Myanmar', countryCode: '+95' },
    { value: 'NAM', label: 'Namibia', countryCode: '+264' },
    { value: 'NRU', label: 'Nauru', countryCode: '+674' },
    { value: 'NPL', label: 'Nepal', countryCode: '+977' },
    { value: 'NLD', label: 'Netherlands', countryCode: '+31' },
    { value: 'NCL', label: 'New Caledonia', countryCode: '+687' },
    { value: 'NZL', label: 'New Zealand', countryCode: '+64' },
    { value: 'NIC', label: 'Nicaragua', countryCode: '+505' },
    { value: 'NER', label: 'Niger', countryCode: '+227' },
    { value: 'NGA', label: 'Nigeria', countryCode: '+234' },
    { value: 'NIU', label: 'Niue', countryCode: '+683' },
    { value: 'NFK', label: 'Norfolk Island', countryCode: '+672' },
    { value: 'MNP', label: 'Northern Mariana Islands', countryCode: '+1-670' },
    { value: 'NOR', label: 'Norway', countryCode: '+47' },
    { value: 'OMN', label: 'Oman', countryCode: '+968' },
    { value: 'PAK', label: 'Pakistan', countryCode: '+92' },
    { value: 'PLW', label: 'Palau', countryCode: '+680' },
    { value: 'PSE', label: 'Palestine', countryCode: '+970' },
    { value: 'PAN', label: 'Panama', countryCode: '+507' },
    { value: 'PNG', label: 'Papua New Guinea', countryCode: '+675' },
    { value: 'PRY', label: 'Paraguay', countryCode: '+595' },
    { value: 'PER', label: 'Peru', countryCode: '+51' },
    { value: 'PHL', label: 'Philippines', countryCode: '+63' },
    { value: 'PCN', label: 'Pitcairn', countryCode: '+64' },
    { value: 'POL', label: 'Poland', countryCode: '+48' },
    { value: 'PRT', label: 'Portugal', countryCode: '+351' },
    { value: 'PRI', label: 'Puerto Rico', countryCode: '+1-787' },
    { value: 'QAT', label: 'Qatar', countryCode: '+974' },
    { value: 'REU', label: 'Réunion', countryCode: '+262' },
    { value: 'ROU', label: 'Romania', countryCode: '+40' },
    { value: 'RUS', label: 'Russia', countryCode: '+7' },
    { value: 'RWA', label: 'Rwanda', countryCode: '+250' },
    { value: 'BLM', label: 'Saint Barthélemy', countryCode: '+590' },
    { value: 'SHN', label: 'Saint Helena, Ascension and Tristan da Cunha', countryCode: '+290' },
    { value: 'KNA', label: 'Saint Kitts and Nevis', countryCode: '+1-869' },
    { value: 'LCA', label: 'Saint Lucia', countryCode: '+1-758' },
    { value: 'MAF', label: 'Saint Martin (French part)', countryCode: '+590' },
    { value: 'SPM', label: 'Saint Pierre and Miquelon', countryCode: '+508' },
    { value: 'VCT', label: 'Saint Vincent and the Grenadines', countryCode: '+1-784' },
    { value: 'WSM', label: 'Samoa', countryCode: '+685' },
    { value: 'SMR', label: 'San Marino', countryCode: '+378' },
    { value: 'STP', label: 'Sao Tome and Principe', countryCode: '+239' },
    { value: 'SAU', label: 'Saudi Arabia', countryCode: '+966' },
    { value: 'SEN', label: 'Senegal', countryCode: '+221' },
    { value: 'SRB', label: 'Serbia', countryCode: '+381' },
    { value: 'SYC', label: 'Seychelles', countryCode: '+248' },
    { value: 'SLE', label: 'Sierra Leone', countryCode: '+232' },
    { value: 'SGP', label: 'Singapore', countryCode: '+65' },
    { value: 'SXM', label: 'Sint Maarten (Dutch part)', countryCode: '+1-721' },
    { value: 'SVK', label: 'Slovakia', countryCode: '+421' },
    { value: 'SVN', label: 'Slovenia', countryCode: '+386' },
    { value: 'SLB', label: 'Solomon Islands', countryCode: '+677' },
    { value: 'SOM', label: 'Somalia', countryCode: '+252' },
    { value: 'ZAF', label: 'South Africa', countryCode: '+27' },
    { value: 'SGS', label: 'South Georgia and the South Sandwich Islands', countryCode: '+500' },
    { value: 'ESP', label: 'Spain', countryCode: '+34' },
    { value: 'LKA', label: 'Sri Lanka', countryCode: '+94' },
    { value: 'SDN', label: 'Sudan', countryCode: '+249' },
    { value: 'SUR', label: 'Suriname', countryCode: '+597' },
    { value: 'SJM', label: 'Svalbard and Jan Mayen', countryCode: '+47' },
    { value: 'SWE', label: 'Sweden', countryCode: '+46' },
    { value: 'CHE', label: 'Switzerland', countryCode: '+41' },
    { value: 'SYR', label: 'Syrian Arab Republic', countryCode: '+963' },
    { value: 'TWN', label: 'Taiwan, Province of China', countryCode: '+886' },
    { value: 'TJK', label: 'Tajikistan', countryCode: '+992' },
    { value: 'TZA', label: 'Tanzania, United Republic of', countryCode: '+255' },
    { value: 'THA', label: 'Thailand', countryCode: '+66' },
    { value: 'TLS', label: 'Timor-Leste', countryCode: '+670' },
    { value: 'TGO', label: 'Togo', countryCode: '+228' },
    { value: 'TKL', label: 'Tokelau', countryCode: '+690' },
    { value: 'TON', label: 'Tonga', countryCode: '+676' },
    { value: 'TTO', label: 'Trinidad and Tobago', countryCode: '+1-868' },
    { value: 'TUN', label: 'Tunisia', countryCode: '+216' },
    { value: 'TUR', label: 'Turkey', countryCode: '+90' },
    { value: 'TKM', label: 'Turkmenistan', countryCode: '+993' },
    { value: 'TCA', label: 'Turks and Caicos Islands', countryCode: '+1-649' },
    { value: 'TUV', label: 'Tuvalu', countryCode: '+688' },
    { value: 'UGA', label: 'Uganda', countryCode: '+256' },
    { value: 'UKR', label: 'Ukraine', countryCode: '+380' },
    { value: 'ARE', label: 'United Arab Emirates', countryCode: '+971' },
    { value: 'GBR', label: 'United Kingdom', countryCode: '+44' },
    { value: 'USA', label: 'United States', countryCode: '+1' },
    { value: 'URY', label: 'Uruguay', countryCode: '+598' },
    { value: 'UZB', label: 'Uzbekistan', countryCode: '+998' },
    { value: 'VUT', label: 'Vanuatu', countryCode: '+678' },
    { value: 'VEN', label: 'Vene zuela', countryCode: '+58' },
    { value: 'VNM', label: 'Viet Nam', countryCode: '+84' },
    { value: 'WLF', label: 'Wallis and Futuna', countryCode: '+681' },
    { value: 'ESH', label: 'Western Sahara', countryCode: '+212' },
    { value: 'YEM', label: 'Yemen', countryCode: '+967' },
    { value: 'ZMB', label: 'Zambia', countryCode: '+260' },
    { value: 'ZWE', label: 'Zimbabwe', countryCode: '+263' }
  ];
};

export default CountryList;