export const countries = [
    { name: "United States", code: "US", phoneCode: "+1" },
    { name: "Canada", code: "CA", phoneCode: "+1" },
    { name: "Japan", code: "JP", phoneCode: "+81" },
    { name: "Germany", code: "DE", phoneCode: "+49" },
    { name: "France", code: "FR", phoneCode: "+33" },
    { name: "United Kingdom", code: "GB", phoneCode: "+44" },
    { name: "China", code: "CN", phoneCode: "+86" },
    { name: "India", code: "IN", phoneCode: "+91" },
    { name: "Australia", code: "AU", phoneCode: "+61" },
    { name: "Brazil", code: "BR", phoneCode: "+55" },
    { name: "South Africa", code: "ZA", phoneCode: "+27" },
    { name: "Mexico", code: "MX", phoneCode: "+52" },
    { name: "Nigeria", code: "NG", phoneCode: "+234" },
    { name: "Argentina", code: "AR", phoneCode: "+54" },
    { name: "Russia", code: "RU", phoneCode: "+7" },
    { name: "Italy", code: "IT", phoneCode: "+39" },
    { name: "Spain", code: "ES", phoneCode: "+34" },
    { name: "South Korea", code: "KR", phoneCode: "+82" },
    { name: "Netherlands", code: "NL", phoneCode: "+31" },
    { name: "Saudi Arabia", code: "SA", phoneCode: "+966" },
    { name: "Turkey", code: "TR", phoneCode: "+90" },
    { name: "Indonesia", code: "ID", phoneCode: "+62" },
    { name: "Thailand", code: "TH", phoneCode: "+66" },
    { name: "Philippines", code: "PH", phoneCode: "+63" },
    { name: "Vietnam", code: "VN", phoneCode: "+84" },
    { name: "Colombia", code: "CO", phoneCode: "+57" },
    { name: "Iran", code: "IR", phoneCode: "+98" },
    { name: "Egypt", code: "EG", phoneCode: "+20" },
    { name: "Malaysia", code: "MY", phoneCode: "+60" },
    { name: "Singapore", code: "SG", phoneCode: "+65" },
    { name: "New Zealand", code: "NZ", phoneCode: "+64" },
    { name: "Portugal", code: "PT", phoneCode: "+351" },
    { name: "Belgium", code: "BE", phoneCode: "+32" },
    { name: "Sweden", code: "SE", phoneCode: "+46" },
    { name: "Norway", code: "NO", phoneCode: "+47" },
    { name: "Finland", code: "FI", phoneCode: "+358" },
    { name: "Denmark", code: "DK", phoneCode: "+45" },
    { name: "Czech Republic", code: "CZ", phoneCode: "+420" },
    { name: "Greece", code: "GR", phoneCode: "+30" },
    { name: "Hungary", code: "HU", phoneCode: "+36" },
    { name: "Ireland", code: "IE", phoneCode: "+353" },
    { name: "Ukraine", code: "UA", phoneCode: "+380" },
    { name: "Iceland", code: "IS", phoneCode: "+354" },
    { name: "Slovakia", code: "SK", phoneCode: "+421" },
    { name: "Slovenia", code: "SI", phoneCode: "+386" },
    { name: "Estonia", code: "EE", phoneCode: "+372" },
    { name: "Latvia", code: "LV", phoneCode: "+371" },
    { name: "Lithuania", code: "LT", phoneCode: "+370" },
    { name: "Bulgaria", code: "BG", phoneCode: "+359" },
    { name: "Romania", code: "RO", phoneCode: "+40" },
    { name: "Moldova", code: "MD", phoneCode: "+373" },
    { name: "Albania", code: "AL", phoneCode: "+355" },
    { name: "Bosnia and Herzegovina", code: "BA", phoneCode: "+387" },
    { name: "Serbia", code: "RS", phoneCode: "+381" },
    { name: "Montenegro", code: "ME", phoneCode: "+382" },
    { name: "North Macedonia", code: "MK", phoneCode: "+389" },
    { name: "Kosovo", code: "XK", phoneCode: "+383" },
    { name: "Belarus", code: "BY", phoneCode: "+375" },
    { name: "Kazakhstan", code: "KZ", phoneCode: "+7" },
    { name: "Uzbekistan", code: "UZ", phoneCode: "+998" },
    { name: "Azerbaijan", code: "AZ", phoneCode: "+994" },
    { name: "Georgia", code: "GE", phoneCode: "+995" },
    { name: "Armenia", code: "AM", phoneCode: "+374" },
    { name: "Kuwait", code: "KW", phoneCode: "+965" },
    { name: "Qatar", code: "QA", phoneCode: "+974" },
    { name: "Bahrain", code: "BH", phoneCode: "+973" },
    { name: "Oman", code: "OM", phoneCode: "+968" },
    { name: "Jordan", code: "JO", phoneCode: "+962" },
    { name: "Lebanon", code: "LB", phoneCode: "+961" },
    { name: "Syria", code: "SY", phoneCode: "+963" },
    { name: "Yemen", code: "YE", phoneCode: "+967" },
    { name: "Iraq", code: "IQ", phoneCode: "+964" },
    { name: "Afghanistan", code: "AF", phoneCode: "+93" },
    { name: "Bangladesh", code: "BD", phoneCode: "+880" },
    { name: "Sri Lanka", code: "LK", phoneCode: "+94" },
    { name: "Maldives", code: "MV", phoneCode: "+960" },
    { name: "Brunei", code: "BN", phoneCode: "+673" },
    { name: "Myanmar", code: "MM", phoneCode: "+95" },
    { name: "Cambodia", code: "KH", phoneCode: "+855" },
    { name: "Laos", code: "LA", phoneCode: "+856" },
    { name: "Mongolia", code: "MN", phoneCode: "+976" },
    { name: "Nepal", code: "NP", phoneCode: "+977" },
    { name: "Bhutan", code: "BT", phoneCode: "+975" },
    { name: "Tanzania", code: "TZ", phoneCode: "+255" },
    { name: "Kenya", code: "KE", phoneCode: "+254" },
    { name: "Uganda", code: "UG", phoneCode: "+256" },
    { name: "Rwanda", code: "RW", phoneCode: "+250" },
    { name: "Ethiopia", code: "ET", phoneCode: "+251" },
    { name: "Zambia", code: "ZM", phoneCode: "+260" },
    { name: "Zimbabwe", code: "ZW", phoneCode: "+263" },
    { name: "Ghana", code: "GH", phoneCode: "+233" },
    { name: "Ivory Coast", code: "CI", phoneCode: "+225" },
    { name: "Senegal", code: "SN", phoneCode: "+221" },
    { name: "Cameroon", code: "CM", phoneCode: "+237" },
    { name: "Togo", code: "TG", phoneCode: "+228" },
    { name: "Benin", code: "BJ", phoneCode: "+229" },
    { name: "Burkina Faso", code: "BF", phoneCode: "+226" },
    { name: "Mali", code: "ML", phoneCode: "+223" },
    { name: "Niger", code: "NE", phoneCode: "+227" },
    { name: "Chad", code: "TD", phoneCode: "+235" },
    { name: "Central African Republic", code: "CF", phoneCode: "+236" },
    { name: "South Sudan", code: "SS", phoneCode: "+211" },
    { name: "Somalia", code: "SO", phoneCode: "+252" },
    { name: "Sierra Leone", code: "SL", phoneCode: "+232" },
    { name: "Tanzania", code: "TZ", phoneCode: "+255" },
    { name: "Malawi", code: "MW", phoneCode: "+265" },
    { name: "Lesotho", code: "LS", phoneCode: "+266" },
    { name: "Swaziland", code: "SZ", phoneCode: "+268" },
    { name: "Dominican Republic", code: "DO", phoneCode: "+1-809" },
    { name: "Honduras", code: "HN", phoneCode: "+504" },
    { name: "Guatemala", code: "GT", phoneCode: "+502" },
    { name: "El Salvador", code: "SV", phoneCode: "+503" },
    { name: "Paraguay", code: "PY", phoneCode: "+595" },
    { name: "Chile", code: "CL", phoneCode: "+56" },
    { name: "Uruguay", code: "UY", phoneCode: "+598" },
    { name: "Cuba", code: "CU", phoneCode: "+53" },
    { name: "Jamaica", code: "JM", phoneCode: "+1-876" },
    { name: "Trinidad and Tobago", code: "TT", phoneCode: "+1-868" },
    { name: "Barbados", code: "BB", phoneCode: "+1-246" },
    { name: "Bahamas", code: "BS", phoneCode: "+1-242" },
    { name: "Saint Lucia", code: "LC", phoneCode: "+1-758" },
    { name: "Saint Vincent and the Grenadines", code: "VC", phoneCode: "+1-784" },
    { name: "Grenada", code: "GD", phoneCode: "+1-473" },
    { name: "Antigua and Barbuda", code: "AG", phoneCode: "+1-268" },
    { name: "Dominica", code: "DM", phoneCode: "+1-767" },
];
